### ISSUE TITLE
makefile cleanups?

### ISSUE THREAD

**Issue by sagiegurari** [sunshine-protocol/sunshine-bounty-ui#12]
Really cool project. However, i think the makefile there is hard to maintain due to all the duplication.
i'll give an example:

```toml
[tasks.android-armv7-release]
private = true
condition = { env_true = ["RELEASE"] }
command = "cargo"
args = [
  "ndk", 
  "--platform", 
  "${ANDROID_PLATFORM_VERSION}", 
  "--target", 
  "armv7-linux-androideabi", 
  "build",
  "--release"
  ]

[tasks.android-i686-release]
private = true
condition = { env_true = ["RELEASE"] }
command = "cargo"
args = [
  "ndk", 
  "--platform", 
  "${ANDROID_PLATFORM_VERSION}", 
  "--target", 
  "i686-linux-android", 
  "build",
  "--release"
  ]
```

These 2 are the same except the target value.
there are a lot of ways to solve this. one way is this:

```toml
[tasks.android-release]
private = true
condition = { env_true = ["RELEASE"], env_set = ["ANDROID_TARGET"] }
command = "cargo"
args = [
  "ndk", 
  "--platform", 
  "${ANDROID_PLATFORM_VERSION}", 
  "--target", 
  "${ANDROID_TARGET}", 
  "build",
  "--release"
]

[tasks.android-armv7-release]
private = true
env = { ANDROID_TARGET = "armv7-linux-androideabi" }
run_task = "android-release"

[tasks.android-i686-release]
private = true
env = { ANDROID_TARGET = "i686-linux-android" }
run_task = "android-release"
```
